### ISSUE TITLE
Socket gets called over ws if server is wss

### ISSUE THREAD

**Issue by kmathmann** [webpack-contrib/webpack-serve#102] opened 2018-04-17 11:49 UTC
* Operating System: Windows 10
* Node Version: 8.10.0
* NPM Version: 5.6.0
* webpack Version: 4.1.1
* webpack-serve Version: 0.3.1

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve ./webpack/webpack.dev.config.js
```

##### webpack.config.js

```js
const config = {
    // ...
    serve: {
        host: 'example.com',
        https: {
            cert: fs.readFileSync(path.join(__dirname, 'ssl', 'ssl.crt')),
            key: fs.readFileSync(path.join(__dirname, 'ssl', 'ssl.key')),
        }
    }
};
```

### Expected Behavior
Server runs on https/wss and the frontend connects to 'wss://example.com:8081'.
### Actual Behavior
Server runs on https/wss and the frontend tries to connect to unsecure 'ws://example.com:8081'.
Same behavior without  the host option.

Also the HTTP url printed into the console uses http as protocol
```console
i ｢hot｣: WebSocket Server Listening at localhost:8081
i ｢serve｣: Project is running at http://localhost:8080
```
### How Do We Reproduce?
Run webpack-serve over https with a valid certificate like described in the webpack.config.js
 snipped.

**Comment by shellscape** [comment] 2018-04-19 14:48
Thanks for the issue :beer: 

I'm not sure this is an actual bug and may be an issue in your environment, as I cannot reproduce the same on my end. If this is an actual bug, it's likely going to be in `webpack-hot-client` rather than `webpack-serve` and the issue will be around this block of code: https://github.com/webpack-contrib/webpack-hot-client/blob/5e2953c41128f70b4662a80d530d968121ba9d1f/lib/client/socket.js#L11. I'll leave this open for discussion and upstream tracking. A PR is welcome to resolve any issue found.

**Comment by shellscape** [comment] 2018-05-28 20:14
Please see my response on #144. As there's been no traction on this issue and we're unable to reproduce on our end, we're going to close this one.

**Closed by shellscape** 2018-05-28 20:14 UTC
Labels: c³ ⋅ need more info, c¹ ⋅ discussion, waiting on upstream
