### ISSUE TITLE
HTTPS option requires manual hot.https: true

### ISSUE THREAD

**Issue by lukewis** [webpack-contrib/webpack-serve#162] opened 2018-06-05 17:03 UTC
It's possible I have a configuration error, but I tried to follow README as closely as possible.  I'm using devcert-cli to generate certificates.  Seems very similar to #144.

* Operating System: MacOS 10.13.3
* Node Version: 8.9.4
* NPM Version: 5.8.0
* webpack Version: 4.8.3
* webpack-serve Version: 1.0.2

This issue is for a:

- [X] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve ./webpack.config.js
```

##### webpack.config.js

[webpack.config.js](https://github.com/lukewis/webpack-serve-https-issue/blob/master/webpack.config.js)

### Expected Behavior
- Page serves and alert message says "Hello World"

### Actual Behavior
- Page loads with errors in javascript console.
- Errors are because websocket connection is attempted over a non-ssl channel

### How Do We Reproduce?

[https://github.com/lukewis/webpack-serve-https-issue](https://github.com/lukewis/webpack-serve-https-issue)

**Comment by shellscape** [comment] 2018-06-05 17:35
Thanks for the issue 🍺  I think you've stumbled across a legitimate bug here with the `https` option. You definitely shouldn't have to configure that manually. We've got a new version coming up soon and we'll make sure this bug is fixed in that.

**Comment by zackify** [comment] 2018-06-05 21:34
I'm having the same issue. If I add the hot part, it tries to use ssl, but has this error: 

![image](https://user-images.githubusercontent.com/449136/41004094-b2cdac26-68e6-11e8-9370-b6d11a3ba794.png)

**Comment by XEngine** [comment] 2018-06-08 10:42
same issue as @zackify  with this config

```javascript 
serve: {
        "port": 9000,
        "https": {
            key: fs.readFileSync(path.resolve('./webpack/lo.key')),
            cert: fs.readFileSync(path.resolve('./webpack/lo.crt'))
        },
        "hot": {
            https: true
        },
        'http2': true
    }
```

**Comment by shellscape** [comment] 2018-06-08 13:00
@zackify @XEngine when an issue has been opened and has been acknowledged to be a bug, you don't need to reply with a "same" or "me too" response. It actually doesn't contribute to the issue, only creates extra noise and notifications for the issue. Instead, use the [reaction button ](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to lend support to the original post, or a particular existing reply.

**Comment by eubenesa** [comment] 2018-06-09 02:59
@lukewis Are you able to get both WebSocket server listening at and project running at the same `webpackserve.test:8081`?

**Comment by lukewis** [comment] 2018-06-11 12:34
@eubenesa Not entirely sure I understand the question.  If I don't specify a port in the config file, I get this by default:
```
ℹ ｢hot｣: WebSocket Server Listening at webpackserve.test:8081
ℹ ｢serve｣: Project is running at https://webpackserve.test:8080
```
When the client attempts to connect, I see this error in Chrome devtools
```
socket.js:18 WebSocket connection to 'wss://webpackserve.test:8081/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
```
If I attempt to force the http server and websocket server to use the same port (not sure if this is what you were asking):
```
serve: {
        host: "webpackserve.test",
        https: {
            key: fs.readFileSync("webpackserve.test.key"),
            cert: fs.readFileSync("webpackserve.test.cert")
        },
        hot: {
            https: true
        },
        port: 8081
    }
```
Then I get an address in use error (which makes sense I think?):
```
ℹ ｢hot｣: WebSocket Server Listening at webpackserve.test:8081
✖ ｢serve｣:  { Error: listen EADDRINUSE 127.0.0.1:8081
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8081 }
```

**Comment by eubenesa** [comment] 2018-06-11 16:26
@lukewis Yup, that's exactly what I was asking (same port)! I have been getting the same `EADDRINUSE` error, but we should be able to use the same port (as designed?), right?

**Comment by shellscape** [comment] 2018-06-20 17:56
This has been resolved and will be available in the next version release.

**Closed by shellscape** 2018-06-20 17:56 UTC
Labels: kind 🐛  bug, p¹ 🔥🔥🔥 critical, v⁵ ⋅ next

**Comment by madhavarshney** [comment] 2018-06-20 18:12
@shellscape - Is using the same port for both webpack-dev-middleware and webpack-hot-client also covered by #171?  If not, I'll create a new issue for that with its use case.

**Comment by shellscape** [comment] 2018-06-20 18:33
@madhavarshney using the same port is not supported by this project because it can cause problems. when the project was initially launched the http server and socket server used the same port. That was changed to avoid conflicts and connection errors. Unfortunately this will not be changed (back to allowing the same port).

**Comment by bennidhamma** [comment] 2018-06-26 21:59
I just upgraded to 2.0.0-beta.2 and I'm still seeing the `socket.js:19 WebSocket connection to 'wss://ben.maven.io:4430/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR` error that other people have reported in this bug. 

Even with the `https` option set to true for the hotClient, it doesn't appear that the websockets are being served via SSL:

```
$ curl -k https://ben.maven.io:4430
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

$ curl http://ben.maven.io:4430
Upgrade Required

```

I can't tell from the history of this issue whether the scope of the fix applies to issues with devcert and https, or to the necessity of manually configuring the `https` option in the `hotClient` configuration object.

Is this the right issue for the SSL protocol error in websockets? Or should I open a new issue?

**Comment by shellscape** [comment] 2018-06-26 22:54
@bennidhamma thanks for checking in. if you've got some bad behavior with `webpack-hot-client` (which looks like what you're reporting), please report the issue on that repo. If you've got some bad behavior with the beta, please add onto the beta PR or open a new issue tagged with "beta:"

**Comment by shellscape** [comment] 2018-06-27 01:33
(This should still be created as a separate issue in `webpack-hot-client`) I did some digging to find out what's going on, because our test apps and setups in this project worked as "expected."

- If you're passing a `server` instance via the options, and that server is an HTTPS server (`https.Server`), then setting `hotClient.https = true` is required. Otherwise the WebSocket protocol won't be `wss` and that'll be a problem.
- If a cert/key or pass/pfx combo is being passed via options, then the WebSocket Server in `hot-client` can and will spawn a regular http.Server to handle WebSocket requests, and the protocol has to stay `ws://`, so `hotClient.https = true` here is needed, and it'll cause problems. 

So it looks like the documentation for `hot-client` needs some clarification.

**Comment by bennidhamma** [comment] 2018-06-27 17:40
Thank you @shellscape. I'm just kind of confused and haven't been able to get a few free hours to sit down and grok the relationship between webpack-hot-client, serve, the old dev server. I'll take a look at webpack-hot-client now.

**Comment by shellscape** [comment] 2018-06-27 17:53
@bennidhamma no worries. here's kind of a crude tree breakdown of both projects:

```
webpack-dev-server
  |__ Express
  |__ webpack-dev-middleware
  |__ webpack/hot/(client script) (https://github.com/webpack/webpack/blob/master/hot/dev-server.js)
  |__ SockJS
  
webpack-serve
  |__ Koa
  |__ koa-webpack
      |__ webpack-dev-middleware
      |__ webpack-hot-client
          |__ Native `WebSocket
```

`dev-middleware` takes care of the compiler and filesystem watching.
`hot-client` takes care of keeping an eye on the compiler and telling the client when it should update. 
`koa-webpack` takes care of composing `dev-middleware` correctly for Koa Middleware. 

Overall the `webpack-serve` methodology and separation of concerns is much more efficient and allows the project to pivot much faster. It also allows people running their own Koa servers to utilize the best parts, in whole or separately. The client script in `hot-client` is far better (biased opinion of course) than what ships with webpack proper. Similar to `webpack-hot-middleware` except that it does a lot of configuration for you automatically and utilizes WebSockets.
