### ISSUE TITLE
Using hot-client with https and http2 results in error

### ISSUE THREAD

**Issue by KeKsBoTer** [webpack-contrib/webpack-serve#258] opened 2018-08-03 11:22 UTC
When I try to use the webpack-hot-client with **https** and set **http2** in the webpack-server options to true, this results in the following error (when opening website in browser):
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onread (net.js:660:25)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
```

* Operating System: Windows 7
* Node Version: v10.7.0
* NPM Version: 6.1.0
* webpack Version: 4.16.4
* webpack-serve Version: 2.0.2

### Expected Behavior

Browser should connect to websocket over https.

### Actual Behavior

Error described above.

### Code

```js
  // webpack.config.js
  ....
  serve: {
        content: "www/",
        http2: true,
        https: {
            key: fs.readFileSync('./cert/localhost.key'),
            cert: fs.readFileSync('./cert/localhost.cert'),
        },
        hotClient: {
            https: true,
        }
    }
```

### How Do We Reproduce?

Setup webpack-serve with https and enable http2.

**Comment by huijiewei** [comment] 2018-08-03 12:48
Duplicate of #241

**Comment by alexander-akait** [comment] 2018-09-18 09:52
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.

**Closed by alexander-akait** 2018-09-18 09:52 UTC
