### ISSUE TITLE
Needs webpack 4 mode specification

### ISSUE THREAD

**Issue by benwiley4000** [webpack-contrib/webpack-serve#61] opened 2018-03-15 11:09 UTC
* Operating System: elementaryOS 0.4.1
* Node Version: 8.9.0
* NPM Version: 5.7.1
* webpack Version: 4.1.1
* webpack-serve Version: 0.2.0

This issue is for a:

- [ ] **bug**
- [X] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve --mode development
```

### Expected Behavior

I should be able to pass the webpack 4 mode to webpack-serve to tell webpack which mode I want to use. This works with webpack-dev-server.

### Actual Behavior

The option is ignored and I get:

```
WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or
'production' to enable defaults for this environment. 
```
### New Feature Use Case

Often I want to reuse the same config but sometimes run it in development mode and sometimes in production mode. Rather than coding it anywhere, I prefer to just pass it as a flag to the CLI.

**Comment by shellscape** [comment] 2018-03-15 13:38
Duplicate of #44. Reasons why this won't happen are in that issue. Please try searching issues before posting a new one in the future.

**Closed by shellscape** 2018-03-15 13:38 UTC
Labels: x² ⋅ duplicate

**Comment by benwiley4000** [comment] 2018-03-15 14:07
@shellscape My mistake, I apologize. I'll respond in that issue.
