### ISSUE TITLE
Could you plan add error overlay?

### ISSUE THREAD

**Issue by budarin** [webpack-contrib/webpack-serve#193] opened 2018-06-24 17:14 UTC
* Operating System: any
* Node Version: any
* NPM Version: any
* webpack Version: 4
* webpack-serve Version: current

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

### Expected Behavior
Need to have error overlay window like weback-dev-server has

### Actual Behavior
there is no error overlay

### New Feature Use Case
add to options ```overlay: boolean```

it's easy to add this feature - have a look at this [repo](https://github.com/smooth-code/error-overlay-webpack-plugin) - modifications only need for discovery serve key in webpack options and fix registering error middleware for koa syntax

**Comment by shellscape** [comment] 2018-06-24 17:18
Thanks for the issue :beer:

Please do try searching issues. There is a duplicate of this request here: https://github.com/webpack-contrib/webpack-serve/issues/4

**Closed by shellscape** 2018-06-24 17:18 UTC
Labels: kind✨ feature, x² ⋅ duplicate

**Comment by G-Rath** [comment] 2018-07-01 21:28
@budarin if you're still wanting this, over the weekend I created & published [`webpack-serve-overlay`](https://github.com/G-Rath/webpack-serve-overlay) that uses the overlay from `webpack-dev-server`.

It should be exactly what you're after.

**Comment by budarin** [comment] 2018-07-01 22:31
@G-Rath 
it's great! thanks!
