### ISSUE TITLE
I have error after last release: Error: Flags were specified that were not recognized:    --r  Not sure what you mean there

### ISSUE THREAD

**Issue by budarin** [webpack-contrib/webpack-serve#214] opened 2018-07-09 22:32 UTC
* Operating System: MacOS
* Node Version: 10.6.0
* NPM Version: 6.2.0-next.1
* webpack Version: 4.15.1
* webpack-serve Version: 2.0.1

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

there was no any error before last release

##### CLI Command

```console
  webpack-serve -r ./config/webpack/client/register-ts.js --config ./config/webpack/client/webpack.config.babel.js
```
### Expected Behavior
run server without the error

### Actual Behavior
fails to start with the error

### How Do We Reproduce?
try to run client script on the [project](https://github.com/budarin/react-ssr-bootstrap-project)

**Comment by shellscape** [comment] 2018-07-09 22:40
Not exactly a great issue there. Always include error messages in the body and choose succinct titles.

This is a duplicate of #213

**Closed by shellscape** 2018-07-09 22:40 UTC
Labels: x² ⋅ duplicate
