### ISSUE TITLE
Support starting server on a unix socket

### ISSUE THREAD

**Issue by kesne** [webpack-contrib/webpack-serve#85] opened 2018-03-30 01:01 UTC
* Operating System: N/A
* Node Version: N/A
* NPM Version: N/A
* webpack Version: N/A
* webpack-serve Version: N/A

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

### New Feature Use Case

Right now, the code uses `get-port` to get a port. This is great, but one other way to start servers is on a unix socket. The API for doing this in node is passing the socket file rather than a port number. I imagine a simple way to support this would be checking if the port is a path (maybe a string starting with `/`?) and bypass the `getPort` checks if that is the case.

**Comment by shellscape** [comment] 2018-03-30 01:09
Thanks for opening an issue and filling out the template, but this is a duplicate of #67. Please do search the issues next time around, and continue discussion on that issue.

**Closed by shellscape** 2018-03-30 01:09 UTC
Labels: x² ⋅ duplicate

**Comment by kesne** [comment] 2018-03-30 01:11
@shellscape FWIW you seemed open to implementing it in that issue, so I think closing this issue is a little hasty. I'll go reply there, and we can re-open that one.

**Comment by shellscape** [comment] 2018-03-30 01:14
Hasty, no. Duplicates should be discussed on the original issue.
