### ISSUE TITLE
404 Not Found: webpack-serve returns "Not found" & doesn't save webpack-ed assets

### ISSUE THREAD

**Issue by wzup** [webpack-contrib/webpack-serve#92] opened 2018-04-01 16:29 UTC
* Operating System: `Ubuntu 16.04.3 LTS`
* Node Version: `v8.9.4`
* NPM Version: `5.6.0`
* webpack Version: `4.4.1` `version modified by @d3viant0ne based on log output`
* webpack-serve Version: `^0.3.0`

This issue is for a:

- [ ] **bug**
- [ ] **modification** request
- [ ] **feature** request

### Code
```javascript
// serve.config.js

const util = require('util');
const path = require('path');
const serve = require('webpack-serve');
const wpConfig = require('./webpack.config.js');
let port = 3000;
let entryPoint = path.resolve(__dirname, 'dist');
let serverConfig = {
    host: 'localhost',
    compiler: null, // An instance of a webpack compiler || null
    content: entryPoint, // The path from which content will be served
    port: port,
    config: wpConfig,    // The webpack config to serve. Alias for <config>.
    on: {
        listening: () => {
            console.log(util.inspect('  Listening on port: ' + port, {colors: true, depth: 0}));
            console.log(util.inspect('  Serving from: ' + entryPoint, {colors: true, depth: 0}));
        }
    },
    hot: true,           // Instruct the client not to apply Hot Module Replacement patches
};
serve(serverConfig);
```

##### CLI Command

```console
  $ node serve.config.js
```

##### webpack.config.js
https://gist.github.com/wzup/bf6e374135617242d7f2081bcba75c52

### Expected Behavior
1) `/dist` directory is populated with files (Webpack is configured to save all asset files to `/dist`)
2) Only one entry point `index.html`. No any other separate pages. All browser routes are served by `react-router`. The `webpack-serve` DOES NOT have or serve routes. I mean:
```
site.com => index.html
site.com/foo => index.html
site.com/foo/bar => index.html
```

### Actual Behavior
1) `/dist` directory is empty. Although webpack outputs that all assets are generated all right. See output below (1)
2)  `webpack-serve` tries to serve routes itself, doesn't send requests to `index.html` and so that always returns `404 Not found`. 
```
// I have react-router to serve "login" page with LoginComponent. But I get 404
site.com/login => 404 Not found
```

### How Do We Reproduce?
Same way

### Question
What's wrong with `webpack-serve`? What do I miss? Why doesn't it work as expected? How solve/configure it?

(1)
Files are generated by Webpack just fine. But they are absent in `/dist` directory:
```console
user@comp:~/apps/bnk.com/client$ node serve.config.js 

ℹ ｢serve｣: Subscribed to 'listening' event
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢hot｣: WebSocket Server Listening at localhost:8081
ℹ ｢serve｣: Project is running at http://localhost:3000
ℹ ｢serve｣: Server URI copied to clipboard
'  Listening on port: 3000'
'  Serving from: /home/user/app/client/dist'
ℹ ｢hot｣: webpack: Compiling Done
ℹ ｢wdm｣: Hash: 7ea88cefb84494ef7bd5
Version: webpack 4.4.1
Time: 26804ms
Built at: 2018-4-1 19:01:04
                               Asset       Size  Chunks             Chunk Names
                      bundle-main.js   6.92 MiB    main  [emitted]  main
                         favicon.ico   1.12 KiB          [emitted]  
5522b7ef581cebc7d94a593d9f15270f.png   1.83 KiB          [emitted]  
4676ca58a2779e52f150f8b9f8681471.png   1.66 KiB          [emitted]  
8c332a96dea4c204da7399bbf3afc565.png    1.6 KiB          [emitted]  
0dac4644cbf5d8ca296c545ae747233a.png   2.23 KiB          [emitted]  
094c84221f657f496dc7c68331ef433d.png    2.1 KiB          [emitted]  
e19279dc63c136d94d418aaf915123dc.png   1.77 KiB          [emitted]  
9301ea2bda1097698c886127b903af01.png   3.01 KiB          [emitted]  
                         bundle-0.js   4.51 KiB       0  [emitted]  
                         bundle-1.js     51 KiB       1  [emitted]  
                         bundle-2.js   2.14 KiB       2  [emitted]  
                         bundle-3.js   1.31 MiB       3  [emitted]  
                         bundle-4.js   4.67 MiB       4  [emitted]  
                         bundle-5.js   6.76 MiB       5  [emitted]  
                         bundle-6.js    369 KiB       6  [emitted]  
                          index.html  406 bytes          [emitted]  
Entrypoint main = bundle-main.js
[./node_modules/prop-types/index.js] 956 bytes {main} [built]
[./node_modules/react-dom/index.js] 59 bytes {main} [built]
[./node_modules/react-hot-loader/index.js] 41 bytes {main} [built]
[./node_modules/react-router-redux/lib/index.js] 1.92 KiB {main} [built]
[./node_modules/react/react.js] 56 bytes {main} [built]
[./node_modules/webpack-hot-client/client/hot.js] (webpack)-hot-client/client/hot.js 4.9 KiB {main} [built]
[./node_modules/webpack-hot-client/client/index.js?728233e7-d088-4467-b20d-5a073a3f1427] (webpack)-hot-client/client?728233e7-d088-4467-b20d-5a073a3f1427 1.86 KiB {main} [built]
[./src/components/Root.js] 3.56 KiB {main} [built]
[./src/constants/data.js] 1.44 KiB {main} [built]
[./src/favicon.ico] 57 bytes {main} [built]
[./src/index.js] 4.87 KiB {main} [built]
[./src/store/configureStore.js] 2.15 KiB {main} [built]
[./src/styles/style.scss] 1.71 KiB {main} [built]
   [0] multi ./src/index.js 28 bytes {main} [built]
   [1] multi webpack-hot-client/client?728233e7-d088-4467-b20d-5a073a3f1427 ./src/index.js 40 bytes {main} [built]
    + 1518 hidden modules
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.41 MiB       0  
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 1.11 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢hot｣: WebSocket Client Connected
```

**Comment by d3viant0ne** [comment] 2018-04-01 18:55
That may very well be one of the best looking bug reports I have seen in quite some time

**Comment by d3viant0ne** [comment] 2018-04-01 18:57
Disregard, read the logs. I have updated your original post accordingly

**Comment by shellscape** [comment] 2018-04-01 23:51
> /dist directory is empty. Although webpack outputs that all assets are generated all right. See output below (1)

Correct. `webpack-dev-middleware` uses a `MemoryFileSystem` and does not write files to disk. That is not a bug.

> webpack-serve tries to serve routes itself, doesn't send requests to index.html and so that always returns 404 Not found.

Correct. You need to implement `history-api-fallback` if you want React to handle the routes. There is an add-on example for that in the `docs/`. That is not a bug.

I'll leave this one open for discussion for a while, but on the surface this is not a bug. If you'd like to put together a **minimal** repo (that means without all the added cruft of sass loaders, etc. Just a singular react entrypoint) that fails one you have `history-api-fallback` implemented, then we can take a look at it as a bug. While I cheers you for a thorough issue 🍻  this is a support request, as you have a config that doesn't quite work.

I encourage you to try and debug this and submit a PR if you feel this is actually a bug. Working with the source may be enlightening.

**Comment by erosenberg** [comment] 2018-04-23 18:32
@shellscape the `history-api-fallback` worked for me. In my opinion there should be a simpler way to add the flag or set a parameter for the server instance.

i.e.

```
const config = {
    [...],
    serveConfig: {
        hot: true,
        historyApiFallback: true,
        port: 8000
    }
}
```

or even:

```
const serveConfig = { ... };
module.exports.serve = webpackServe(serveConfig);
```

I haven't read enough to know if this was deliberate or just not developed yet, but I thought I would mention it. Other than that, I love this SO much better than `webpack-dev-server`.

**Comment by shellscape** [comment] 2018-04-24 00:08
@erosenberg glad you're liking the project. this project differs from `webpack-dev-server` in that it allows users to add complexity needed for their specific use, rather than tying up large amounts of complexity trying to cater to every user's need. it was very much a carefully considered and planned move away from `webpack-dev-server` and the net result is a faster, more easily maintained, and nimble product.

**Comment by shellscape** [comment] 2018-04-24 00:08
Closing since we've got a confirmation that the suggested solution does indeed work.

**Closed by shellscape** 2018-04-24 00:08 UTC
Labels: c⁴ ⋅ question, webpack v4

**Comment by m4ss1m0g** [comment] 2018-05-02 16:19
I think is better to write this info on README page with a minimal functional example.
